import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/app/components/Navbar/Navbar'
import Sidebar from '@/app/components/Sidebar/Sidebar'
import Footer from './components/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-theme="halloween" lang="en">
      <body className={`${inter.className}`}>
        <Sidebar />
        <Navbar />
        <div className="w-[80%] mx-auto p-5">
        {children}
        </div>
        {/* <Footer /> */}
        </body>
    </html>
  )
}
